### ISSUE TITLE
[BUG] Can't run tests with extension, but can run in CLI

### ISSUE THREAD

**Issue by mahy-ks-hussain** [orta/vscode-jest#1190]
**Describe the bug**
I am able to run tests from the CLI, and despite the output saying `[error] failed to retrieve test file list. TestExplorer might show incomplete test items`, I can still see the tests in the Test Explorer. However, I'm not able to run any of the tests, and I'm not sure what's going wrong in my config. Also, the testing button in the toolbar (flask) doesn't show up on startup until I run any Jest command.

My folder/workspace structure is like this:

- root
- - project1
- - project2

**To Reproduce**
1. Click the testing button in the toolbar (flask).
2. Run any test.
3. Error in output:
```
TestRun "hello-world:runTest: orta.vscode-jest:TestProvider:hello-world:7 (0)" started
/bin/sh: 1: npm: not found
```
4. The same happens if I run a test with CodeLens.

Note: A sample repo will help us identify the bug much faster. 🙏
Affected repo: https://github.com/[mahy-ks-hussain/exercism_javascript](https://github.com/mahy-ks-hussain/exercism_javascript)

**Expected behavior**
I am expecting the tests to be able to run similar to how it is in the CLI.

**Screenshots**
![Image](https://github.com/user-attachments/assets/0f24eddd-5ae2-483b-8993-20cb7c4415b2)

**Environment (please complete the following information):**
- vscode-jest version: 6.2.5
- `node -v`: 22.11.0
- `npm -v` or `yarn --version`: np 10.9.0
- jest or react-scripts (if you haven’t ejected) version: 29.6.4
- your vscode-jest settings:
    - jest.jestCommandLine? npm test --
    - jest.runMode? on-demand
    - jest.outputConfig? none
- Operating system: Ubuntu 24.04

**Prerequisite**
- are you able to run jest from the command line? Yes
- where do you run jest CLI from? In each subfolder (for now)
- how do you run your tests from the command line? In each subfolder, with npm run test

**Additional context**
I am still very, *very* new to JavaScript and its environment setup, and this is my first time trying it out.

**Comment by connectdotz** [comment]
Hi @mahy-ks-hussain, thanks for providing the repo. I tried running it, and the tests worked fine on my end (though the tests in the `lasagna` package failed, all tests in `hello-world` passed). This suggests the issue might be related to your shell environment setup.

If you can run tests via the CLI (is it `npm test`?) but get an `npm not found` error with the extension, this indicates the extension's spawned shell doesn't have the correct environment setup—specifically, the PATH to `npm` may be missing. This [link](https://github.com/jest-community/vscode-jest?tab=readme-ov-file#intermittent-errors-for-npmyarnnode-command-not-found-during-test-run-or-debugging) explains the issue in detail and provides potential solutions, which might help you resolve it.

I also noticed that the `test` scripts in both `package.json` files are defined as `"test": "jest ./*"`. Since Jest will automatically find and run all test files based on the patterns in the Jest config, you don’t need to include `./*`.

Let me know if you’re still having issues.
