### ISSUE TITLE
Disable Debug button

### ISSUE THREAD

**Issue by Cael6** [orta/vscode-jest#175]
Is there any configuration to disable the debug button. It is making VS code behave strangely. First it adds a new line making it awkward to visualise my code. I have also experienced scrolling while I'm typing with the new debug functionality.

**Comment by seanpoulter** [comment]
It doesn't look like there was an option added with the pull request but it'd be quick to add for anyone interested.

**Comment by bogdan-calapod** [comment]
I'm also having this problem - after every new line I have to scroll up

**Comment by smith** [comment]
FWIW I would much rather have the lens say "Expected value to be (using ===): true, Received: false" than "Debug." Is there an existing feature request for this?

**Comment by Moeriki** [comment]
I am having weird scrolling behavior as well on Code-Insiders.

**Comment by bogdan-calapod** [comment]
This is starting to get in my way while coding - for example when I have the following files:

component.js:
```javascript

import React, { Component } from 'react'

class Component extends Component {

  render () {
    return <div>
    </div>
  }
}

export default Component
````

And the following component.test.js:
```javascript
import React from 'react'
import {shallow} from 'enzyme'
import Component from './'

describe('Component', () => {
  it('shadow renders', () => { shallow(<Component />) })

  it('renders at least one image', () => {
    const wrapper = shallow(<Component />)
    expect(wrapper.find('img').length).toBeGreaterThan(0)
  })
})
```

While trying to write between the components' `<div>` to write the render content, the "debug" indicator flips around after every keystroke and I can't write anything.

I've currently resorted to running Jest watch mode in the integrated terminal, but it isn't ideal. This plugin was working amazingly well until this feature dropped.

**VSCode version:** 1.18.1
**OS:** Windows 10 Fall Creators Update (Build 1709)

**Comment by rraziel** [comment]
Seems to me like it is more a bug than an enhancement: VSCode can quickly become fairly unusable.

**Comment by orta** [comment]
It's pretty easy to add this as a feature 👍 

I'm at the end of a deadline, so I have no time, but I can review and merge stuff

**Comment by bogdan-calapod** [comment]
Any updates on this ? Currently this plugin makes vscode unusable, at least for me.

**Comment by seanpoulter** [comment]
@smith, no we don't have an existing feature request for changing the "Debug" text to be the error message.

Can we help you get started on a PR @bogdan-calapod?

**Comment by bogdan-calapod** [comment]
Actually I'd be interested - I might have a couple hours free in the weekend to look into it, but I haven't worked on vscode extensions until now. 

Apart from the [official documentation](https://code.visualstudio.com/docs/extensions/overview) is there any other resource I should be aware of to get started ?

**Comment by seanpoulter** [comment]
Awesome. I've found those docs a good start to understand what the extension lifecycle. There are also docs for the [`vscode` API](https://code.visualstudio.com/docs/extensionAPI/vscode-api) that help.

If you follow the [Contributing](https://github.com/orta/vscode-jest/#want-to-contribute) notes to clone the repo, open it in Code, and start debugging with the "Launch Extension" debug config you're halfway there. Since it would take most of your time getting familiar with the code, here's the gist:
  * settings are defined in the `"contributes"` section of `package.json` and `IPluginSettings`
  * don't get hung up on when the CodeLens `provideCodeLenses(...)` is called -- follow those decorations

**Comment by bogdan-calapod** [comment]
Sounds great - I'll be getting to work and will get back when I have something

**Comment by Huddo121** [comment]
For future time travellers the setting you're looking for is `"jest.enableCodeLens": false`

**Comment by seanpoulter** [comment]
Oh no, @Huddo121! Any other feedback/features to make the CodeLens useful? I've got the PR in to fix which documents it displays on.

**Comment by Huddo121** [comment]
@seanpoulter 
I would of been happy with a delay setting, so that all the problems that I was seeing with the code lens (code scrolling and code jumping around being the biggest for me) could be mitigated. So `"jest.codeLensDelay": 2500` would prevent the lens from displaying unless I had stopped typing for 2.5 seconds.

The lens also sometimes appears in weird places
![image](https://user-images.githubusercontent.com/1518405/34181633-215b4cec-e567-11e7-9da5-f4ee9ab13422.png)

I've also got one sitting here between two import statements, at the top of a file.

When I click on the debug lens, a message pops up saying "Cannot find jest.js file!". I don't know what that file is, a quick search hasn't turned up anything, and I haven't needed it before now, so perhaps linking to some documentation about whatever that file is in the message would be beneficial.

**Comment by seanpoulter** [comment]
Those are some great ideas @Huddo121. Thanks for the feedback.
<br/>


>I would of been happy with a delay setting, so that all the problems that I was seeing with the code lens (code scrolling and code jumping around being the biggest for me) could be mitigated.

How about waiting until there are test results in to add the CodeLens?
<br/>

>The lens also sometimes appears in weird places

Yep, it wasn't This should be fixed by a recent PR. Let me know if it's acting up.
<br/>

> When I click on the debug lens, a message pops up saying "Cannot find jest.js file!".

Any chance that's a repo we can troubleshoot? If you're using a non-standard test script command, clicking on Debug will make that error message appear. It's similar to #193.

**Comment by specialistvlad** [comment]
Who from 2020.
1. Open settings
2. Typo "code lens" in search bar
3. disabled top check box
4. Profit

**Comment by seanpoulter** [comment]
Are those instructions to disable the Code Lens everywhere @specialistvlad?

**Comment by specialistvlad** [comment]
> Are those instructions to disable the Code Lens everywhere @specialistvlad?

Definitely enough for me 😊

**Comment by wangfupeng1988** [comment]
I disabled here then It is worked, I use Javascript

![Uploading image.png…]()
