### ISSUE TITLE
Not working properly with create-react-app-typescript

### ISSUE THREAD

**Issue by scolyer** [orta/vscode-jest#190]
### Environment

1. `node -v`: v8.9.1
2. `npm -v`: 5.5.1
4. `npm ls react-scripts` (if you haven’t ejected): react-scripts-ts@2.8.0

1. Operating system: Mac OS X High Sierra 10.13.1

### Steps to Reproduce

Install vscode-jest into VSCode

### Expected Behavior

IDE highlights jest tests

### Actual Behavior

No change to IDE, however Jest appears in the bottom bar with a tick.

---

**Comment by seanpoulter** [comment]
Thanks for reporting your issue @scolyer. I'm not familiar with `create-react-app-typescript` which makes it hard to reproduce this issue following your instructions. Did you set up your app following [these instructions](https://github.com/wmonk/create-react-app-typescript#tldr)?

**Comment by seanpoulter** [comment]
We'll have to wait to confirm how @scolyer set up his workspace, but I've reproduced this using the instructions linked above. When an app is bootstrapped with `create-react-app` and `react-scripts-ts` Jest starts with the default command and doesn't match any tests.

Adding `react-scripts-ts` to the family of "react scripts" we [look for in the `node_modules/`](https://github.com/orta/vscode-jest/blob/2.5.0/src/helpers.ts#L12) fixes the issue, and starts tests with `npm test --` instead of `jest`.

**Comment by scolyer** [comment]
Hi @seanpoulter thanks for looking at this so promptly!
Yes I used the instructions you linked above. Looking forward to the next release.

**Comment by seanpoulter** [comment]
Extra thanks to @orta for reviewing and publishing just as quick. Hopefully it's working today @scolyer.

**Comment by scolyer** [comment]
Yes, it’s working now! Thanks!
