### ISSUE TITLE
Support external config file

### ISSUE THREAD

**Issue by luizbon** [orta/vscode-jest#26]
Version 1.6.1 is working with my environment, thanks @orta !

Since I'm using an external configuration file to run my jest tests, it fails. It is possible to add a new setting where I define the path to a config file?

I can try to do a PR with some guidance, never worked with VS Code extensions.

**Comment by orta** [comment]
So the key will be to add a configuration to this:  https://github.com/orta/vscode-jest/blob/master/package.json#L55-L59

Then inside the [jest_process](https://github.com/orta/vscode-jest/blob/master/src/lib/jest_process.ts#L27) you need to add support for the extra arg `--config thingy.json` 

_however_ - because we have a separation of extension and library (due to https://github.com/facebook/jest/issues/2183 ) you cannot just plonk:

```js
  const jestSettings: any = workspace.getConfiguration("jest");
  const path = normalize(jestSettings.pathToJest);
```

in there, I'd recommend adding it a "default args" to the [workspace](https://github.com/orta/vscode-jest/blob/master/src/lib/project_workspace.ts) and pulling it out of that
