### ISSUE TITLE
Run Jest inside sub-folder

### ISSUE THREAD

**Issue by luisrudge** [orta/vscode-jest#6]
![image](https://cloud.githubusercontent.com/assets/941075/20448254/3d521be0-adca-11e6-889d-a36b0d7ad091.png)

I'm getting this error when trying to watch jest:
`command 'extension.jest.startJest' not found`

So, after I installed the extension, nothing happens:
![image](https://cloud.githubusercontent.com/assets/941075/20448271/527bcf7a-adca-11e6-9fdb-cbf9ce9ff1c9.png)

**Comment by orta** [comment]
Jest is running, those white dots represent test that have not been ran yet ( because it only runs in watcher mode ) ( you can see the status in the blue bar at the bottom )

Now that Jest 16 is out, I can do my final polish pass for this extension 👍

**Comment by luisrudge** [comment]
right, but the dots never turn green/red.
I'm on jest@17.0.2. Maybe that's the issue?

**Comment by orta** [comment]
I'm unsure, I'm afraid you'd have to clone and run the project in dev mode to see the JSON being passed around to figure that one out

**Comment by pietbrauer** [comment]
I am also unable to execute it from the command palette. However if I open the subdirectory for my client code it starts the watcher automatically and runs the tests when I change something.

My guess is that it doesn't work if your client is in a subdirectory, e.g. `client/src/`. Can you confirm @luisrudge?

**Comment by orta** [comment]
The command itself does nothing ( I forgot to remove it ) Jest will always be running in a project that includes the jest module

**Comment by pietbrauer** [comment]
I see, so the real "issue" is that it should also run when contained in a subdirectory in a monorepo?

**Comment by orta** [comment]
Yeah 👍

**Comment by orta** [comment]
I have none of those to use as an example ( in all of Artsy's codebases )

**Comment by pietbrauer** [comment]
I was using and older version of this template: https://github.com/serverless/serverless-graphql it has all the frontend code in `client/src/` instead of the root folder. But the plugin seems to work with the latest version of the template. 🙂

**Comment by orta** [comment]
Rock 👍 

might be just be broken when using an older version of Jest, I wanted to add something to ensure a minimum version of 17 at some point

**Comment by luisrudge** [comment]
here's the error I'm having with the new version
```
Exception raised: Process failed: spawn node_modules/.bin/jest ENOENT
Error Parsing :c:\git\oss\auth0-progressive-profiling\code\components\Card.spec.js. - TypeError: Cannot read property 'forEach' of undefined
 
```

**Comment by luizbon** [comment]
Also getting Exception raised: Process failed: spawn node_modules/.bin/jest ENOENT
I'm using an external jest configuration if it helps.

**Comment by orta** [comment]
@luisrudge  is that one windows? ( I wonder if I need to do something different on windows ) can you also check to see if `node_modules/.bin/jest` exists?

@luizbon where is your jest binary? I wanted to get around to making this [configurable](https://github.com/orta/vscode-jest/blob/master/src/jest_runner.ts#L17) or be derived from the `package.json`

**Comment by luisrudge** [comment]
I'm on windows indeed. `c:\git\oss\project\node_modules\.bin\jest` exists

**Comment by luizbon** [comment]
@orta I've checked and node_modules/.bin/jest is there, but I don't have any jest configuration inside the package.json since I'm using an external configuration file.

**Comment by luisrudge** [comment]
I have my config inside the package.json file

**Comment by luisrudge** [comment]
I still get `command 'io.orta.jest.start' not found`

**Comment by orta** [comment]
even on 1.1.0? Even then, it should auto start and you can click on the status bar to see whats going on
![screen shot 2016-11-28 at 18 29 23](https://cloud.githubusercontent.com/assets/49038/20680824/985cc852-b598-11e6-940b-3bfa592dd5dc.png)

**Comment by luisrudge** [comment]
I guess, since the command is not found, nothing works. I can't even see the status bar.

**Comment by luizbon** [comment]
After the last update, still not working for me. :(

**Comment by orta** [comment]
Then I'd recommend cloning the repo and taking a look at what's going on in debug mode - I'm out of ideas

**Comment by orta** [comment]
Or making a sample project that exhibits that behaviour so I can take a look at it

**Comment by orta** [comment]
I got a `ReferenceError: document is not defined` error, which may be what you're seeing - can you check with 1.3.2, think I got it.

As commands are added at runtime, if the extension crashes before they are registered, it would not show - which this crash would have done

**Comment by luisrudge** [comment]
`command 'io.orta.jest.start' not found` 😭

**Comment by imoby** [comment]
I am also getting a similar error where it throws the document is not defined. 

![image](https://cloud.githubusercontent.com/assets/6380855/24179834/9ed0a894-0e7f-11e7-8430-84c4a306963b.png)

**Comment by dearfrankg** [comment]
Ok it's not just me.  I miss my green dots.

**Comment by Domiii** [comment]
Also having that problem. Jest Debug Console says: 

> Exception raised: Process failed: spawn jest ENOENT

Took me a while, but I finally figured it out:

# Final solution

1. Create new `runJest.sh` file (in workspace root)
1. In my case, it contains: `cd relative/path/to/test/root && npm test # NOTE: path contains `package.json` and have a `test` script defined`
1. In VSCode's `settings.json`, add: `"jest.pathToJest": "sh runJest.sh"`

(NOTE: This even works on Windows if you have Cygwin installed and properly configured)

# Problem Solving Process

1. The [official vscode-jest troubleshooting guide](https://github.com/jest-community/vscode-jest/blob/master/README.md#troubleshooting) tells you to set your workspace's `jest.pathToJest` setting, however there is no documentation on how its supposed to work.
1. Looked at [the source code](https://github.com/jest-community/vscode-jest/tree/master/src/helpers.ts#L73) and saw one special case returning `npm test --`, realizing it's actually ill-named: it's a command-line/shell command and not a path.
   * Turns out that `jest` from the error message (`spawn jest ENOENT`) refers to the value of `pathToJest`.
1. First I tried (in my sample project): `"jest.pathToJest": "cd projects/todomvc/examples/vanilla-es6/ && npm test"`.
   * No dice. `cd`'ing won't work.
   * Also note that VS project variables/macros (such as `${workspaceFolder}` won't be recognized.
1. Finally came up with final solution mentioned above.
